### ISSUE TITLE
Error while ionic building using prod mode in latest version(1.1.1) of plugin

### ISSUE THREAD

**Issue by hparth** [jonaszuberbuehler/ion-affix#17] opened 2017-12-12 11:02 UTC
On Ionic 3 build (v3.8.0), Plugin version (1.0.9) is working fine but Plugin version (1.1.1) causing the issue :-

Error: Metadata version mismatch for module /Users/mccuser/Documents/Projects/App/workspace/App/node_modules/ion-affix/dist/ion-affix.module.d.ts, found version 4, expected 3

**Comment by jonaszuberbuehler** [comment] 2017-12-12 12:40
Can you post your `ionic info` please?

**Comment by hparth** [comment] 2017-12-13 11:22
Ionic Info :-
cli packages: (D:\Users\username\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.0
    npm  : 5.5.1
    OS   : Windows 7

**Comment by jonaszuberbuehler** [comment] 2017-12-13 14:24
@hparth Just to make sure: did you try `rm -rf node_modules` and `npm install`? There are some issues with similar error message on ionic github where this solved the problem.

**Comment by jonaszuberbuehler** [comment] 2017-12-18 15:54
@hparth Is this still an issue after deleting and reinstalling `node_modules`?

**Comment by hparth** [comment] 2017-12-19 16:33
Yes it's still there.

**Comment by jonaszuberbuehler** [comment] 2017-12-19 20:12
Could you please post your package.json (or the relevant parts of it)? I'm not able to reproduce this.

**Comment by hparth** [comment] 2017-12-20 06:48
package.json ->

{
  "name": "App",
  "version": "0.0.1",
  "author": "Mobile Team",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "angular/common": "4.4.4",
    "angular/compiler": "4.4.4",
    "angular/compiler-cli": "4.4.4",
    "angular/core": "4.4.4",
    "angular/forms": "4.4.4",
    "angular/http": "4.4.4",
    "angular/platform-browser": "4.4.4",
    "angular/platform-browser-dynamic": "4.4.4",
    "angular/tsc-wrapped": "^4.3.4",
    "ionic-native/android-fingerprint-auth": "4.1.0",
    "ionic-native/camera": "^4.2.0",
    "ionic-native/core": "^4.2.0",
    "ionic-native/keyboard": "^4.2.0",
    "ionic-native/native-storage": "^4.2.0",
    "ionic-native/splash-screen": "4.4.2",
    "ionic-native/status-bar": "4.2.0",
    "ionic-native/touch-id": "4.2.0",
    "ionic-native/unique-device-id": "^4.4.2",
    "ionic/storage": "2.1.3",
    "ng-idle/core": "2.0.0-beta.12",
    "ng-idle/keepalive": "2.0.0-beta.12",
    //Add at @ sign in above all packages, because it's no allowed here :(

  "angular2-useful-swiper": "^4.0.6",
    "ibm-mfp-web-sdk": "^8.0.2017021409",
    "ion-affix": "1.0.9",
    "ionic-angular": "3.8.0",
    "ionicons": "3.0.0",
    "moment": "^2.18.1",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.0.0",
    "typescript": "2.3.3"
  },
  "cordovaPlugins": [
    "cordova-plugin-splashscreen",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "ionic-plugin-keyboard",
    "cordova-plugin-statusbar",
    "cordova-plugin-spinner-dialog",
    "cordova-plugin-mfp",
    "cordova-plugin-dialogs",
    "cordova-plugin-globalization",
    "cordova-plugin-okhttp"
  ],
  "cordovaPlatforms": [
    {
      "platform": "android",
      "version": "",
      "locator": "android"
    },  "homepage": "http://a.com/",  "homepage": "http://a.com/",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "Mobile Application"
}

Ionic CLI - 3.19.0

**Comment by jonaszuberbuehler** [comment] 2017-12-20 16:52
@hparth Can you upgrade your project to latest ionic version? Using angular 5.x will fix the problem.

**Comment by jonaszuberbuehler** [comment] 2018-01-13 22:54
Closing issue for now.

**Closed as completed by jonaszuberbuehler** 2018-01-13 22:54 UTC
